name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Name of Variable'
    required: true
    default: 'World'
  name_aks_cluster:
    required: false
    default: "testando"
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}
      shell: bash
    - id: test
      run: echo "TESTANDO EXPORT DE VARIAVEL"
      shell: bash
      env:
        TESTE: ${{ inputs.name_aks_cluster }}
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash
   
