name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Name of Variable'
    required: true
    default: 'World'
  singer:
    required: true
    default: "Still Pulse"
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
  my-name:
    description: "Meu nome"
    value: ${{ steps.my-name-generator.outputs.my-name}}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)"  >> $GITHUB_OUTPUT
      shell: bash
    - id: name-of-singer
      run: echo "The name of singer is" ${{ inputs.singer }}
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash
    - id: my-name-generator 
      run: echo "my-name=Trinta"  >> $GITHUB_OUTPUT; echo GITHUB $GITHUB_OUTPUT
      shell: bash
    - id: test-variable
      run: echo "TESTE"
      shell: bash
    - id: test-
      run: echo $name_aks_cluster
      shell: bash
