name: 'Hello World'
description: 'Greet someone'
inputs:
  name_aks_cluster:
    required: true
    default: "testando"
runs:
  using: "composite"
  steps:
    - run: goodbye.sh
      shell: bash
      env:
        TESTE: ${{ inputs.name_aks_cluster }}
